# Generated by Django 4.0.4 on 2022-06-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='projectID',
            new_name='project',
        ),
    ]
