# Generated by Django 4.0.4 on 2022-06-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rename_projectid_issue_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('timecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
