# Generated by Django 4.0.4 on 2022-06-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issuecomment_issue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueComment',
            new_name='Comment',
        ),
    ]
